databases:
  users:
    db_location: /home/pi/Documents/databases
    report: false
    resources: [
      users.csv
    ]
  expenses:
    handle: 
    db_location: /home/pi/Documents/databases
    report: true
  guests:
    db_location: /home/pi/Documents/databases
    report: true