databases:
  users:
    db_path: ./databases/db/users.db
    backup_path: ./databases/backup/users.db.bkp
    init_path: ./sql/users/init.sql
    init_data_path: ./secret-data/users.csv
  expenses:
    db_path: ./databases/db/expenses.db
    backup_path: ./databases/backup/expenses.db.bkp
    init_path: ./sql/expenses/init.sql
    init_data_path: null